window.ALLERGEN_LABELS = {
  es: {
    G: "Gluten",
    C: "Crustáceos",
    H: "Huevos",
    P: "Pescado",
    N: "Cacahuetes",
    S: "Soja",
    L: "Lácteos",
    F: "Frutos secos",
    Ap: "Apio",
    M: "Mostaza",
    Se: "Sésamo",
    Su: "Sulfitos",
    Al: "Altramuces",
    Mo: "Moluscos"
  },
  en: {
    G: "Gluten",
    C: "Crustaceans",
    H: "Eggs",
    P: "Fish",
    N: "Peanuts",
    S: "Soy",
    L: "Dairy",
    F: "Nuts",
    Ap: "Celery",
    M: "Mustard",
    Se: "Sesame",
    Su: "Sulphites",
    Al: "Lupin",
    Mo: "Molluscs"
  }
};

window.DISH_ALLERGENS = {
  "Mix de queso curado de oveja": ["L"],
  "Chorizo criollo": [],
  "Empanadas criollas de carne o pollo": ["G","H"],
  "Mollejas de ternera al limón": [],
  "Sepia": ["Mo"],
  "Gambas al ajillo": ["C"],
  "Pimientos de Padrón": [],
  "Hummus con chimichurri": [],
  "Parrillada de verduras": [],
  "Mini verduras a la parrilla": [],
  "Champiñones al ajillo": [],
  "Queso provoleta": ["L"],
  "Calamares a la andaluza": ["Mo", "G"],
  "Pulpo braseado con puré de patatas": ["Mo", "L"],

  "Mixta": [],
  "De ventresca": ["P"],
  "Caprese": ["L"],
  "Ensalada mango & cabra deluxe": ["L", "M"],
  "Ensalada sorpresa La Estancia": ["P"],

  "Muslo de pollo deshuesado con patatas fritas": [],
  "Costillas de cerdo a la barbacoa con patatas fritas": ["Su", "M"],
  "Entraña con patatas fritas": [],
  "Chuletas de cordero con patatas fritas": [],
  "Carrillera de cerdo ibérico sobre puré de patatas trufado": ["L"],
  "Entrecot argentino con patatas fritas": [],
  "Solomillo de ternera con patatas fritas": [],
  "Hamburguesa La Estancia con patatas fritas": ["G", "L", "H"],
  "Chuletón de Ávila 500 g con patatas fritas": [],
  "Chuletón de ternera 1 kg / para 2 personas": [],
  "Costillar de ternera a baja temperatura": ["L"],
  "Milanesa napolitana con patatas fritas": ["G", "L", "H"],
  "Milanesa con huevo": ["G", "H"],
  "Parrillada de carnes con patatas fritas / para 2 personas": [],
  "Filete tomahawk 1,1 kg / para 2 personas": ["Su"],
  "T-Bone 850 g": [],
  
  "Lubina con patatas fritas": ["P"],
  "Dorada": ["P"],
  "Salmón con puré de patatas y salsa de mariscos": ["P", "C", "Mo", "L"],
  "Parrillada de mariscos / para 2 personas": ["P", "C", "Mo", "Su"],
  "Milanesa con patatas fritas": ["G", "H"],
  "Hamburguesa con patatas fritas": ["G", "L"],
  "Frutas de estación": [],
  "Panqueque con helado": ["G", "L", "H"],
  "Flan con dulce de leche": ["L", "H"],
  "Coulant de chocolate": ["G", "L", "H"],
  "Brownie con helado de vainilla": ["G", "L", "H", "F"],
  "Tiramisú": ["G", "L", "H"],
  "Copa de helado": ["L"],
  "Surtido de postres": ["G", "L", "H"],
  "Café con leche": ["L"],
  "Cortado": ["L"],
  "Capuccino": ["L"],
  "Bombón": ["L"],
  "Belmonte": ["L"],
  "Irlandés": ["L"],
  "Caña Turia (tostada)": ["G"],
  "Pinta Turia (tostada)": ["G"],
  "Caña Estrella Levante": ["G"],
  "Pinta Estrella Levante": ["G"],
  "Tercios: Estrella Galicia, Alhambra": ["G"],
  "Tercio 0,0%": ["G"],
  "Tercio Reserva Alhambra": ["G"]
};

window.GROUP_ALLERGENS = {
  "Tinto argentino": ["Su"],
  "Rioja": ["Su"],
  "Ribera del Duero": ["Su"],
  "Alicante": ["Su"],
  "Blancos": ["Su"],
  "Rosado": ["Su"],
  "Copas de vino": ["Su"],
  "Cava y cócteles": ["Su"]
};
