window.GALLERY_DATA = {
  categories: [
    { "id": "carnes", "es": "Carnes", "en": "Meats" },
    { "id": "mar", "es": "Mar", "en": "Seafood" },
    { "id": "veggie", "es": "Ensaladas y verduras", "en": "Salads & vegetables" },
    { "id": "postres", "es": "Postres", "en": "Desserts" },
    { "id": "vinos", "es": "Vinos y copas", "en": "Wine & drinks" },
    { "id": "entrantes", "es": "Entrantes", "en": "Starters" },
    { "id": "estancia", "es": "La Estancia", "en": "La Estancia" }
  ],
  items: [
    { "src": "assets/images/gallery/meat1.png", "cat": "carnes", "es": "Entrecot y tinto", "en": "Entrecôte and red wine", "wide": true },
    { "src": "assets/images/gallery/meat2.png", "cat": "carnes", "es": "Corte a la parrilla", "en": "Grilled cut" },
    { "src": "assets/images/gallery/meat3.png", "cat": "carnes", "es": "Emplatado de la casa", "en": "House plating" },
    { "src": "assets/images/gallery/meat4.png", "cat": "carnes", "es": "A la brasa", "en": "Over the fire" },
    { "src": "assets/images/gallery/meat5.png", "cat": "carnes", "es": "Parrillada", "en": "Mixed grill" },
    { "src": "assets/images/gallery/meat6.png", "cat": "carnes", "es": "Carne a punto", "en": "Cooked to order" },
    { "src": "assets/images/gallery/meat7.png", "cat": "carnes", "es": "Corte de ternera", "en": "Beef cut" },
    { "src": "assets/images/gallery/meat8.png", "cat": "carnes", "es": "Mesa larga", "en": "Long table", "wide": true },
    { "src": "assets/images/gallery/meat9.png", "cat": "carnes", "es": "Chuletón", "en": "Ribeye" },
    { "src": "assets/images/gallery/meat10.png", "cat": "carnes", "es": "Entraña", "en": "Skirt steak" },
    { "src": "assets/images/gallery/meat11.png", "cat": "carnes", "es": "Fuego y sal", "en": "Fire and salt" },
    { "src": "assets/images/gallery/meat12.png", "cat": "carnes", "es": "Parrillada de la casa", "en": "House mixed grill", "wide": true },
    { "src": "assets/images/gallery/seafood1.png", "cat": "mar", "es": "Calamares", "en": "Squid", "wide": true },
    { "src": "assets/images/gallery/seafood2.png", "cat": "mar", "es": "Del mar", "en": "From the sea" },
    { "src": "assets/images/gallery/seafood3.png", "cat": "mar", "es": "A la plancha", "en": "Grilled seafood" },
    { "src": "assets/images/gallery/seafood4.png", "cat": "mar", "es": "Pescado de la casa", "en": "House fish" },
    { "src": "assets/images/gallery/seafood5.png", "cat": "mar", "es": "Parrillada de mariscos", "en": "Seafood grill", "wide": true },
    { "src": "assets/images/gallery/veggie1.png", "cat": "veggie", "es": "Parrillada de verduras", "en": "Grilled vegetables", "wide": true },
    { "src": "assets/images/gallery/veggie2.png", "cat": "veggie", "es": "Ensalada de la casa", "en": "House salad" },
    { "src": "assets/images/gallery/veggie3.png", "cat": "veggie", "es": "Verde a la brasa", "en": "Grilled greens" },
    { "src": "assets/images/gallery/veggie4.png", "cat": "veggie", "es": "Ensalada", "en": "Salad" },
    { "src": "assets/images/gallery/postr1.png", "cat": "postres", "es": "Brownie con helado", "en": "Brownie with ice cream", "wide": true },
    { "src": "assets/images/gallery/postr2.png", "cat": "postres", "es": "Postre de la casa", "en": "House dessert" },
    { "src": "assets/images/gallery/drink1.png", "cat": "vinos", "es": "Copa de tinto", "en": "Glass of red" },
    { "src": "assets/images/gallery/drink2.png", "cat": "vinos", "es": "Cóctel", "en": "Cocktail" },
    { "src": "assets/images/gallery/drink4.png", "cat": "vinos", "es": "Bodega", "en": "Cellar", "wide": true },
    { "src": "assets/images/gallery/drink5.png", "cat": "vinos", "es": "Vino de la casa", "en": "House wine" },
    { "src": "assets/images/gallery/drink6.png", "cat": "vinos", "es": "Servicio de copa", "en": "Wine service" },
    { "src": "assets/images/gallery/drink7.png", "cat": "vinos", "es": "Brindis", "en": "A toast" },
    { "src": "assets/images/gallery/drink8.png", "cat": "vinos", "es": "Selección", "en": "The selection" },
    { "src": "assets/images/gallery/drink9.png", "cat": "vinos", "es": "En la barra", "en": "At the bar" },
    { "src": "assets/images/gallery/start1.png", "cat": "entrantes", "es": "Empanadas criollas", "en": "Argentinian empanadas", "wide": true },
    { "src": "assets/images/gallery/place1.png", "cat": "estancia", "es": "La sala", "en": "The dining room", "wide": true },
    { "src": "assets/images/gallery/place2.png", "cat": "estancia", "es": "Mesa puesta", "en": "Table set" },
    { "src": "assets/images/gallery/team1.png", "cat": "estancia", "es": "Luis", "en": "Luis" }
  ]
};
